
led_config_list:
  
  - led_name: "front_right_leds"
    leds_zone: [1, 5]
    channel: 0
    type: "RGB"


  - led_name: "rear_right_leds"
    leds_zone: [50, 75]
    channel: 0
    type: "RGB"


  - led_name: "front_left_leds"
    leds_zone: [11, 15]
    channel: 0
    type: "RGB"


  - led_name: "rear_left_leds"
    leds_zone: [1, 100]
    channel: 0
    type: "RGB"


  - led_name: "all_leds"
    leds_zone: [1, 100]
    channel: 0
    type: "RGB"
