
led_state_list:
  
  - state: "EMERGENCY"
    led_name: "all_leds"
    mode: "blink"
    color: [255, 0, 0, 0]
    ms_on: 900
    ms_off: 900


  - state: "TURN_LEFT"
    led_name: "rear_left_leds"
    mode: "shift"
    color: [0, 0, 255, 0]
    direction: "right"
    speed: 500
    sleep: 500


  - state: "TURN_RIGHT"
    led_name: "rear_right_leds"
    mode: "shift"
    color: [0, 0, 255, 0]
    direction: "left"
    speed: 500
    sleep: 500


#  - state: "FORWARD"
#    led_name: "rear_right_leds"
#    mode: "blink"
#    color: [0, 20, 20, 0]
#    ms_on: 100
#    ms_off: 100


  - state: "STOP"
    led_name: "all_leds"
    mode: "paint"
    color: [102 , 0, 102, 0]


  - state: "MOVING"
    led_name: "all_leds"
    mode: "blink"
    color: [0,255,0, 0]
    ms_on: 500
    ms_off: 500
