
led_config_list:
  
  - led_label: "rear_right_leds"
    leds_zone: [135, 202]
    channel: 0
    type: "RGB"

  - led_label: "rear_left_leds"
    leds_zone: [203, 270]
    channel: 0
    type: "RGB"


  - led_label: "all_leds"
    leds_zone: [1, 270]
    channel: 0
    type: "RGB"
