
led_config_list:
  
  - name: "rear_right_leds"
    leds_zone: [135, 202]
    channel: 0
    type: "RGB"

  - name: "rear_left_leds"
    leds_zone: [203, 270]
    channel: 0
    type: "RGB"


  - name: "all_leds"
    leds_zone: [1, 270]
    channel: 0
    type: "RGB"
