

leds_list:
  
  -name: "led_front_right"
   leds_zone: [1, 5]
   channel: 0
   type: RGB


  -name: "led_rear_right"
   leds_zone: [6, 10]
   channel: 0
   type: RGB


  -name: "led_front_left"
   leds_zone: [11, 15]
   channel: 0
   type: RGB


  -name: "led_rear_left"
   leds_zone: [16, 20]
   channel: 0
   type: RGB

