
led_state_list:
  
  - name: "EMERGENCY"
    mode: "blink"
    color: [20, 0, 0]
    ms_on: 100
    ms_off: 100


  - name: "TURN_LEFT"
    mode: "shift"
    color: [0, 20, 0]
    direction: "left"
    speed: 500
    sleep: 500


  - name: "TURN_RIGHT"
    mode: "shift"
    color: [0, 0, 20]
    direction: "right"
    speed: 500
    sleep: 500


  - name: "FOWARD"
    mode: "blink"
    color: [0, 20, 20]
    ms_on: 100
    ms_off: 100


  - name: "STOP"
    mode: "paint"
    color: [20 , 20, 20]